#!/bin/bash

# Crash on any error
set -e

# Load LXC defaults
if [ -r /etc/default/lxc ]; then
    . /etc/default/lxc
fi

# The install function installs the minimal operating system in the LXC
install() {
    profile_path=$1
    rootfs_dir=$2
    quiet=$3
    debug=$4
    if [ "$quiet" -ne 1 ]; then
        echo 'Deploying container root filesystem ...'
    fi
    tar -C $rootfs_dir -xzf $profile_path
    if [ "$quiet" -ne 1 ]; then
	    echo 'Deployed.'
    fi
}

# Set up the path option
options=$(getopt -o n:p: -l path:,name:,rootfs:,profile:,version:,quiet,debug -- "$@")

if [ $? -ne 0 ]; then
    exit 1
fi

eval set -- "$options"

quiet=0
debug=0

lxc_cache_base="/var/cache/lxc/rainmaker/project"

# Fetch command line parameters
while true; do
    case "$1" in
        -p|--path)      path=$2; shift 2;;
        -n|--name)      name=$2; shift 2;;
        --rootfs)       rootfs=$2; shift 2;;
        --profile)      profile=$2; shift 2;;
        --version)      version=$2; shift 2;;
        --quiet)        quiet=1; shift 1;;
        --debug)        debug=1; shift 1;;
        --)             shift 1; break ;;
        *)              break ;;
    esac
done

if [ -z "$path" ]; then
    echo "'path' parameter is required"
    exit 1
fi

if [ -z "$profile" ]; then
    echo "'profile' parameter is required"
    exit 1
fi

if [ -z "$version" ]; then
    echo "'version' parameter is required"
    exit 1
fi

if [ "$(id -u)" != "0" ]; then
    echo "This script should be run as 'root'"
    exit 1
fi

# detect rootfs
config="$path/config"
# if $rootfs exists here, it was passed in with --rootfs
if [ -z "$rootfs" ]; then
    if grep -q '^lxc.rootfs' $config 2>/dev/null ; then
        rootfs=$(awk -F= '/^lxc.rootfs =/{ print $2 }' $config)
    else
        rootfs=$path/rootfs
    fi
fi

if [ "$quiet" -ne 1 ]; then
    echo "Name: $name"
    echo "Path: $path"
    echo "Profile: $profile"
    echo "Version: $version"
fi

major=`echo $version | cut -d'.' -f1`
lxc_cache_path="$lxc_cache_base/$profile/$major/$version.tgz"

if [ "$quiet" -eq 1 ]; then
    echo "LXC Cache Path: $lxc_cache_path"
fi

if [ ! -f "$lxc_cache_path" ]; then
    echo "Profile root filesystem archive is not present in cache"
    exit 1
fi

install $lxc_cache_path $rootfs $quiet $debug
