#!/bin/bash

# Crash on any error
set -e

# Load LXC defaults
if [ -r /etc/default/lxc ]; then
    . /etc/default/lxc
fi

# The install function installs the minimal operating system in the LXC
install() {
    profile_path=$1
    rootfs_dir=$2
    quiet=$3
    debug=$4
    if [ "$quiet" -ne 1 ]; then
        echo 'Deploying container root filesystem ...'
    fi
    tar -C $rootfs_dir -xzf $profile_path
    if [ "$quiet" -ne 1 ]; then
	    echo 'Deployed.'
    fi
}

# Set up the path option
options=$(getopt -o n:p: -l path:,name:,rootfs:,profile:,version:,downloadhost:,quiet,debug -- "$@")

if [ $? -ne 0 ]; then
    exit 1
fi

eval set -- "$options"

quiet=0
debug=0

lxc_cache_base="/var/cache/lxc/rainmaker/project"

profile_download_host="http://image.rainmaker-dev.com"
if [ -n "$RMK_DOWNLOAD_HOST" ]; then
    profile_download_host="$RMK_DOWNLOAD_HOST"
fi

# Fetch command line parameters
while true; do
    case "$1" in
        -p|--path)      path=$2; shift 2;;
        -n|--name)      name=$2; shift 2;;
        --rootfs)       rootfs=$2; shift 2;;
        --profile)      profile=$2; shift 2;;
        --version)      version=$2; shift 2;;
        --downloadhost) profile_download_host=$2; shift 2;;
        --quiet)        quiet=1; shift 1;;
        --debug)        debug=1; shift 1;;
        --)             shift 1; break ;;
        *)              break ;;
    esac
done

if [ -z "$path" ]; then
    echo "'path' parameter is required"
    exit 1
fi

if [ -z "$profile" ]; then
    profile="rainmaker/default-branch"
fi

if [ -z "$version" ]; then
    version="latest"
fi

if [ "$(id -u)" != "0" ]; then
    echo "This script should be run as 'root'"
    exit 1
fi

# detect rootfs
config="$path/config"
# if $rootfs exists here, it was passed in with --rootfs
if [ -z "$rootfs" ]; then
    if grep -q '^lxc.rootfs' $config 2>/dev/null ; then
        rootfs=$(awk -F= '/^lxc.rootfs =/{ print $2 }' $config)
    else
        rootfs=$path/rootfs
    fi
fi

if [ "$quiet" -ne 1 ]; then
    echo "Name: $name"
    echo "Path: $path"
    echo "Profile: $profile"
    echo "Version: $version"
fi

profile_present=0
if [ "$version" == "latest" ]; then
    if [ "`rprofmgr profile:present $profile | fgrep -i 'Profile present'`" != "" ]; then
        profile_present=1
    fi
else
    if [ "`rprofmgr profile:present $profile --profile-version=$version | fgrep -i 'Profile present'`" != "" ]; then
        profile_present=1
    fi
fi

if [ "$profile_present" -ne 1 ]; then
  echo "Profile is not installed"
else
    if [ "$quiet" -ne 1 ]; then
        echo "Profile is installed"
    fi
fi

# Download rootfs
lxc_cache_path_cmd="rprofmgr profile:version-cache-path $profile"
if [ "$version" != "latest" ]; then
    lxc_cache_path_cmd="$lxc_cache_path_cmd --profile-version=$version"
fi
lxc_cache_path=$($lxc_cache_path_cmd)

if [ "$lxc_cache_path" == "" ]; then
    profile_download_cmd="rprofmgr profile:download-version $profile"
    if [ "$version" != "latest" ]; then
        profile_download_cmd="$profile_download_cmd --profile-version=$version"
    fi
    if [ "$profile_download_host" != "" ]; then
        profile_download_cmd="$profile_download_cmd --download-host=$profile_download_host"
    fi
    $profile_download_cmd
    lxc_cache_path=$($lxc_cache_path_cmd)
fi

if [ "$debug" -eq 1 ]; then
    echo "LXC Cache Path: $lxc_cache_path"
fi

install $lxc_cache_path $rootfs $quiet $debug
